#!/usr/bin/env python3
import argparse

TYPES = [("i8", 8, True), ("u8", 8, False), ("i16", 16, True), ("u16", 16, False), ("i32", 32, True), ("u32", 32, False), ("i64", 64, True), ("u64", 64, False)]
RMW = ["add", "sub", "and", "or", "xor", "exchange"]
OTHER = ["store", "load", "cas_ok", "cas_fail"]
ORDER = "core::atomic::MemoryOrder::SeqCst"

HEADER = """module main;

import core::atomic;
import std::os::file;
import std::result;
import std::slice;

using std::os::{ file };
using std::{ slice };

i32 failures = 0;

void report(i32 code) {
    failures = failures + 1;
    file::File out = file::stdout();
    u8[16] buf;
    usize n = 15;
    buf[15] = 10 as u8;
    u32 v = code as u32;
    while true {
        n = n - 1;
        buf[n] = ((v % 10) + 48) as u8;
        v = v / 10;
        if v == 0 {
            break;
        }
    }
    if !out.write_all(slice::from_raw(&buf[n], 16 - n)).is_ok() {
        return;
    }
}
"""


def wrap(v, bits, signed):
    v &= (1 << bits) - 1
    if signed and v >> (bits - 1):
        v -= 1 << bits
    return v


def apply(op, a, b, bits, signed):
    ua, ub = a & ((1 << bits) - 1), b & ((1 << bits) - 1)
    r = {"add": ua + ub, "sub": ua - ub, "and": ua & ub, "or": ua | ub, "xor": ua ^ ub, "exchange": ub}[op]
    return wrap(r, bits, signed)


def lit(v, t):
    return "((%d) as %s)" % (v, t)


def operands(bits, signed):
    a = wrap(0x5A3C96E1F00F7B2D, bits, signed)
    b = wrap(0x6E0F1234A55A5AA5 if bits == 64 else 0x7E0F1234A55A5AA5, bits, signed)
    if signed:
        a = wrap(-abs(a) if a != 0 else -3, bits, signed)
    return a, b


def generate(ops, widths):
    body = ["public i32 main() {\n"]
    names = []
    code = 0
    for t, bits, signed in TYPES:
        if bits not in widths:
            continue
        a, b = operands(bits, signed)
        for overload in ("ptr", "atomic"):
            for op in ops:
                code += 1
                first = code
                code += 1
                second = code
                v = "v%d" % first
                if overload == "ptr":
                    decl = "    volatile %s %s = %s;\n" % (t, v, lit(a, t))
                    ref = "&%s as volatile %s*" % (v, t)
                    cur = v
                else:
                    decl = "    core::atomic::Atomic(%s) %s;\n    %s.value = %s;\n" % (t, v, v, lit(a, t))
                    ref = "&%s" % v
                    cur = "core::atomic::atomic_load(&%s, %s)" % (v, ORDER)
                if op in RMW:
                    fn = "core::atomic::atomic_" + ("exchange" if op == "exchange" else "fetch_" + op)
                    body.append(decl + "    %s o%d = %s(%s, %s, %s);\n    if o%d != %s { report(%d); }\n    if %s != %s { report(%d); }\n"
                                % (t, first, fn, ref, lit(b, t), ORDER, first, lit(a, t), first, cur, lit(apply(op, a, b, bits, signed), t), second))
                elif op == "store":
                    body.append(decl + "    core::atomic::atomic_store(%s, %s, %s);\n    if %s != %s { report(%d); }\n    if %s != %s { report(%d); }\n"
                                % (ref, lit(b, t), ORDER, cur, lit(b, t), first, cur, lit(b, t), second))
                elif op == "load":
                    body.append(decl + "    if core::atomic::atomic_load(%s, %s) != %s { report(%d); }\n    if %s != %s { report(%d); }\n"
                                % (ref, ORDER, lit(a, t), first, cur, lit(a, t), second))
                else:
                    expected = a if op == "cas_ok" else wrap(a + 1, bits, signed)
                    final = b if op == "cas_ok" else a
                    body.append(decl + "    %s r%d = core::atomic::atomic_compare_exchange(%s, %s, %s, %s, %s);\n    if r%d != %s { report(%d); }\n    if %s != %s { report(%d); }\n"
                                % (t, first, ref, lit(expected, t), lit(b, t), ORDER, ORDER, first, lit(a, t), first, cur, lit(final, t), second))
                names.append("%d %s %s %s result" % (first, t, overload, op))
                names.append("%d %s %s %s memory" % (second, t, overload, op))
    body.append("    return failures;\n}\n")
    return HEADER + "\n" + "".join(body), names


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ops", default=",".join(RMW + OTHER))
    parser.add_argument("--widths", default="8,16,32,64")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    source, names = generate(args.ops.split(","), [int(w) for w in args.widths.split(",")])
    with open(args.out, "w") as f:
        f.write("//! Generated by tests/stdlib/gen_atomic_checks.py --ops %s --widths %s\n" % (args.ops, args.widths))
        f.write("//! Exit code is the number of failed checks; each failing check id is printed.\n")
        f.write("//!\n")
        for n in names:
            f.write("//! %s\n" % n)
        f.write(source)


if __name__ == "__main__":
    main()
